name: push to Dev
on: push

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.4
        id: cache
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
        if: steps.cache-build.outputs.cache-hit != 'true'

  docker-build:
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Get the version
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_SHA} 
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: serious-flight-302114
          image_name: test-flow
          image_tag: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}
          dockerfile: ./Dockerfile  
        
  create-dump:
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - uses: actions/checkout@v2.3.4
      - run: echo "Dump created"
  
  db-migration:
    runs-on: ubuntu-latest
    needs: [ create-dump ]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.4
        id: cache
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
        if: steps.cache-build.outputs.cache-hit != 'true'
      - run: npm run lint 
    
  firebase-deploy:
     runs-on: ubuntu-latest
     needs: cache
     steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.4
        id: cache
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
        if: steps.cache-build.outputs.cache-hit != 'true'
      - run: npm run build 
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: "default"           
  
  update-cluster:
      runs-on: ubuntu-latest
      needs: [ db-migration, docker-build ]
      env:
         PROJECT_ID: ${{ secrets.GKE_PROJECT }}
         GKE_CLUSTER: test-flow
         GKE_ZONE: europe-north1-a
         DEPLOYMENT_NAME: test-flow
         IMAGE: test-flow
         NAME_SPASE: default
         DEPLOYMENT_NAME_CON: nginx-1
      steps:
        - uses: actions/checkout@v2.3.4
        - uses: google-github-actions/setup-gcloud@v0.2.0
          with:
            service_account_key: ${{ secrets.GCP_SERVICE_KEY }}
            project_id: ${{ secrets.GKE_PROJECT }}
        - run: |-
            gcloud --quiet auth configure-docker
        - uses: google-github-actions/get-gke-credentials@v0.2.1
          with:
            cluster_name: ${{ env.GKE_CLUSTER }}
            location: ${{ env.GKE_ZONE }}
            credentials: ${{ secrets.GCP_SERVICE_KEY }}
        - name: Get the version
          run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_SHA}
        - name: update
          run: |-
            kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME_CON=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA --namespace=$NAME_SPASE
            kubectl rollout status deployment/$DEPLOYMENT_NAME --namespace=$NAME_SPASE
            kubectl get services -o wide --namespace=$NAME_SPASE
         
